### ISSUE TITLE
c2ffi fails with an assert

### ISSUE THREAD

**Issue by attila-lendvai** [rpav/c2ffi#19]
i'm on debian stable, happens with both libbluetooth-dev 5.33-1 (testing) and 5.23-2+b1 (stable).

bluez.h:
```
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/ioctl.h>
#include <bluetooth/bluetooth.h>
#include <bluetooth/hci.h>
#include <bluetooth/hci_lib.h>
```

tmp.h:
```
#include "bluez.h"
#include "macros.h"
```

first phase works as expected:
```
c2ffi bluez.h -M macros.h -A x86_64-pc-linux-gnu
```

second phase dies with assert:
```
c2ffi tmp.h -o delme -A x86_64-pc-linux-gnu
[...]
Skipping invalid Decl:
FunctionDecl 0x3273880 </usr/include/bluetooth/bluetooth.h:336:1, col:28> col:7 invalid bt_malloc 'void *(int)'
`-ParmVarDecl 0x32737c0 <col:17, col:24> col:24 invalid size 'int'
c2ffi: /media/store/work/llvm-3.6/include/llvm/ADT/PointerUnion.h:131: T llvm::PointerUnion<const clang::ValueDecl *, const clang::Expr *>::get() const [PT1 = const clang::ValueDecl *, PT2 = const clang::Expr *, T = const clang::Expr *]: Assertion `is<T>() && "Invalid accessor called"' failed.
Aborted
```

when run in gdb the backtrace is:
```
[...]
Skipping invalid Decl:
FunctionDecl 0x2493880 </usr/include/bluetooth/bluetooth.h:336:1, col:28> col:7 invalid bt_malloc 'void *(int)'
`-ParmVarDecl 0x24937c0 <col:17, col:24> col:24 invalid size 'int'
c2ffi: /media/store/work/llvm-3.6/include/llvm/ADT/PointerUnion.h:131: T llvm::PointerUnion<const clang::ValueDecl *, const clang::Expr *>::get() const [PT1 = const clang::ValueDecl *, PT2 = const clang::Expr *, T = const clang::Expr *]: Assertion `is<T>() && "Invalid accessor called"' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff67bb107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff67bb107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff67bc4e8 in __GI_abort () at abort.c:89
#2  0x00007ffff67b4226 in __assert_fail_base (fmt=0x7ffff68eace8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x1393768 "is<T>() && \"Invalid accessor called\"", 
    file=file@entry=0x139378d "/media/store/work/llvm-3.6/include/llvm/ADT/PointerUnion.h", line=line@entry=131, 
    function=function@entry=0x13937c8 "T llvm::PointerUnion<const clang::ValueDecl *, const clang::Expr *>::get() const [PT1 = const clang::ValueDecl *, PT2 = const clang::Expr *, T = const clang::Expr *]")
    at assert.c:92
#3  0x00007ffff67b42d2 in __GI___assert_fail (assertion=0x1393768 "is<T>() && \"Invalid accessor called\"", file=0x139378d "/media/store/work/llvm-3.6/include/llvm/ADT/PointerUnion.h", line=131, 
    function=0x13937c8 "T llvm::PointerUnion<const clang::ValueDecl *, const clang::Expr *>::get() const [PT1 = const clang::ValueDecl *, PT2 = const clang::Expr *, T = const clang::Expr *]") at assert.c:101
#4  0x0000000000410752 in get<clang::Expr const*> (this=<optimized out>) at /media/store/work/llvm-3.6/include/llvm/ADT/PointerUnion.h:131
#5  c2ffi::C2FFIASTConsumer::make_decl (this=<optimized out>, d=<optimized out>, is_toplevel=<optimized out>) at AST.cpp:224
#6  0x000000000040fc10 in c2ffi::C2FFIASTConsumer::HandleDecl (this=0x22b76d0, d=0x269de50, ns=<optimized out>) at AST.cpp:101
#7  0x00000000004121fd in c2ffi::C2FFIASTConsumer::HandleTopLevelDecl (this=0x22b76d0, d=...) at AST.cpp:145
#8  0x000000000078d2ac in clang::ParseAST(clang::Sema&, bool, bool) ()
#9  0x000000000078d062 in clang::ParseAST(clang::Preprocessor&, clang::ASTConsumer*, clang::ASTContext&, bool, clang::TranslationUnitKind, clang::CodeCompleteConsumer*, bool) ()
#10 0x00000000004084ea in main (argc=<optimized out>, argv=<optimized out>) at c2ffi.cpp:94
```

if i run c2ffi only on macros.h (i.e. not on tmp.h) then it fails with a different assert:
```
[...]
macros.h:9703:45: error: expected expression
const long __c2ffi___need_NULL = __need_NULL;
                                            ^
c2ffi: /media/store/work/llvm/tools/clang/lib/Sema/Sema.cpp:249: clang::Sema::~Sema(): Assertion `DelayedTypos.empty() && "Uncorrected typos!"' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff67bb107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff67bb107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff67bc4e8 in __GI_abort () at abort.c:89
#2  0x00007ffff67b4226 in __assert_fail_base (fmt=0x7ffff68eace8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x14ea360 "DelayedTypos.empty() && \"Uncorrected typos!\"", 
    file=file@entry=0x14ea328 "/media/store/work/llvm/tools/clang/lib/Sema/Sema.cpp", line=line@entry=249, function=function@entry=0x14ee2d0 <clang::Sema::~Sema()::__PRETTY_FUNCTION__> "clang::Sema::~Sema()")
    at assert.c:92
#3  0x00007ffff67b42d2 in __GI___assert_fail (assertion=0x14ea360 "DelayedTypos.empty() && \"Uncorrected typos!\"", file=0x14ea328 "/media/store/work/llvm/tools/clang/lib/Sema/Sema.cpp", line=249, 
    function=0x14ee2d0 <clang::Sema::~Sema()::__PRETTY_FUNCTION__> "clang::Sema::~Sema()") at assert.c:101
#4  0x000000000084bd9b in clang::Sema::~Sema() ()
#5  0x000000000043829c in std::default_delete<clang::Sema>::operator()(clang::Sema*) const ()
#6  0x0000000000432c27 in std::unique_ptr<clang::Sema, std::default_delete<clang::Sema> >::~unique_ptr() ()
#7  0x000000000078d07a in clang::ParseAST(clang::Preprocessor&, clang::ASTConsumer*, clang::ASTContext&, bool, clang::TranslationUnitKind, clang::CodeCompleteConsumer*, bool) ()
#8  0x00000000004084ea in main (argc=<optimized out>, argv=<optimized out>) at c2ffi.cpp:94
(gdb) 
```

c2ffi seems to be statically linked to llvm:
```
$ ldd /home/alendvai/workspace/c2ffi/src/c2ffi
	linux-vdso.so.1 (0x00007ffc49fb3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb9350a2000)
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007fb934e7d000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fb934c53000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb934a38000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb93472d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb93442c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb934216000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb933ff9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb933c50000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb9352a6000)
```

this is how i compiled c2ffi:
```
PATH=/media/store/work/llvm-3.6/bin/:$PATH; LDFLAGS=/media/store/work/llvm-3.6/lib/; ./configure --enable-debug
PATH=/media/store/work/llvm-3.6/bin/:$PATH make -j2
```

llvm version:
```
$ svn info
Path: .
Working Copy Root Path: /media/store/work/llvm
URL: http://llvm.org/svn/llvm-project/llvm/branches/release_36
Relative URL: ^/llvm/branches/release_36
Repository Root: http://llvm.org/svn/llvm-project
Repository UUID: 91177308-0d34-0410-b5e6-96231b3b80d8
Revision: 251109
Node Kind: directory
Schedule: normal
Last Changed Author: hans
Last Changed Rev: 240577
Last Changed Date: 2015-06-24 21:50:28 +0200 (Wed, 24 Jun 2015)
```

**Comment by attila-lendvai** [comment]
if i unpull the commit https://github.com/rpav/c2ffi/commit/4c9cca1a690abfcb2e73145ab88766ea2698a3ad then it runs without an assert.

**Comment by rpav** [comment]
I *believe* this should be fixed.  Sorry for the delay.

**Comment by attila-lendvai** [comment]
i've run c2ffi HEAD on the same stuff and it managed to generate the output, so i'm closing it. thanks!
